from django.db import models

# Create your models here.
class IGEDataModel(models.Model):
    status = models.CharField(max_length=50, null=True, blank=True)
    employee_contacted = models.CharField(max_length=10, choices=(("Yes", "Yes"), ("No", "No")))
    manual_intervention_req = models.CharField(max_length=10, choices=(("Yes", "Yes"), ("No", "No")))
    country = models.CharField(max_length=20)
    currency = models.CharField(max_length=20)
    expense_type = models.CharField(max_length=30) 
    submitted_pre_clearance = models.EmailField()
    submitted_pre_clearance_id = models.IntegerField()
    submitted_expense = models.EmailField(null=True, blank=True)
    submitted_expense_id = models.IntegerField(null=True, blank=True)
    submitted_on_behalf_expense = models.EmailField(null=True, blank=True)
    submitted_on_behalf_expense_id = models.IntegerField(null=True, blank=True)
    employee_present = models.CharField(max_length=100)
    transaction_date_expense = models.DateField()
    transaction_date_pre_clearance = models.DateField()
    days_difference = models.IntegerField()
    approved_amount_expense = models.DecimalField(max_digits=18, decimal_places=2)
    actual_amount_expense = models.CharField(max_length=500, null=True, blank=True)
    approved_amount_pre_clearance = models.DecimalField(max_digits=18, decimal_places=2)
    amount_difference = models.DecimalField(max_digits=18, decimal_places=2)
    company_name_expense = models.CharField(max_length=100)
    company_name_pre_clearance = models.CharField(max_length=100) 
    institution_type = models.CharField(max_length=10, choices=(("Public", "Public"), ("Private", "Private")))
    transaction_id = models.BigIntegerField()
    type_of_violation = models.CharField(max_length=100)
    direction = models.CharField(max_length=20, choices=(("Given", "Given"), ("Received", "Received")))
    last_updated = models.DateTimeField(auto_now=True)
