# Generated by Django 3.1.3 on 2021-04-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IGEDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('employee_contacted', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('manual_intervention_req', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('country', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=20)),
                ('expense_type', models.CharField(max_length=30)),
                ('submitted_pre_clearance', models.EmailField(max_length=254)),
                ('submitted_pre_clearance_id', models.IntegerField()),
                ('submitted_expense', models.EmailField(blank=True, max_length=254, null=True)),
                ('submitted_expense_id', models.IntegerField(blank=True, null=True)),
                ('submitted_on_behalf_expense', models.EmailField(blank=True, max_length=254, null=True)),
                ('submitted_on_behalf_expense_id', models.IntegerField(blank=True, null=True)),
                ('employee_present', models.CharField(max_length=100)),
                ('transaction_date_expense', models.DateField()),
                ('transaction_date_pre_clearance', models.DateField()),
                ('days_difference', models.IntegerField()),
                ('approved_amount_expense', models.DecimalField(decimal_places=2, max_digits=18)),
                ('actual_amount_expense', models.CharField(blank=True, max_length=500, null=True)),
                ('approved_amount_pre_clearance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('amount_difference', models.DecimalField(decimal_places=2, max_digits=18)),
                ('company_name_expense', models.CharField(max_length=100)),
                ('company_name_pre_clearance', models.CharField(max_length=100)),
                ('institution_type', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], max_length=10)),
                ('transaction_id', models.BigIntegerField()),
                ('type_of_violation', models.CharField(max_length=100)),
                ('direction', models.CharField(choices=[('Given', 'Given'), ('Received', 'Received')], max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
