# Generated by Django 3.1.3 on 2021-04-30 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ige', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='igedatamodel',
            name='last_updated',
        ),
    ]
