# Generated by Django 3.1.3 on 2021-04-30 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ige', '0002_remove_igedatamodel_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='igedatamodel',
            name='transaction_date_expense',
        ),
        migrations.RemoveField(
            model_name='igedatamodel',
            name='transaction_date_pre_clearance',
        ),
    ]
