# Generated by Django 3.1.3 on 2021-04-30 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ige', '0003_auto_20210430_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='igedatamodel',
            name='submitted_expense_id',
        ),
        migrations.RemoveField(
            model_name='igedatamodel',
            name='submitted_on_behalf_expense_id',
        ),
        migrations.RemoveField(
            model_name='igedatamodel',
            name='submitted_pre_clearance_id',
        ),
    ]
